dependencies:
  - name: postgresql
    version: 8.6.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.installdep.enable

  - name: rabbitmq
    version: 7.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.installdep.enable

  - name: elasticsearch
    version: 7.6.1
    repository: https://helm.elastic.co
    condition: elasticsearch.installdep.enable

  - name: minio
    version: 5.0.10
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: minio.installdep.enable