# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

fabio:
  repository: fabiolb/fabio
  tag: 1.5.8-go1.10
  pullPolicy: IfNotPresent
  
serviceindex:
  repository: reportportal/service-index
  tag: 4.0.0
  pullPolicy: IfNotPresent
  
mongodb:
  repository: mongo
  tag: 3.4
  pullPolicy: IfNotPresent

consul:
  repository: consul
  tag: 1.0.6
  pullPolicy: IfNotPresent
  
serviceauthorization:
  repository: reportportal/service-authorization
  tag: 4.1.0
  pullPolicy: IfNotPresent
  
serviceui:
  repository: reportportal/service-ui
  tag: 4.1.0
  pullPolicy: IfNotPresent

serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 4.1.0
  pullPolicy: IfNotPresent
  
serviceapi:
  repository: reportportal/service-api
  tag: 4.1.0
  pullPolicy: IfNotPresent
  
elasticsearchoss:
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: 6.1.1
  pullPolicy: IfNotPresent


# ingress configuration for the ui
ingress:
  hosts:
    - reportportal.k8.com

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# persistence configuration for elasticsearch, mongodb & consul
persistence:
  elasticsearch:
    enabled: true
    spec:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 10Gi
  mongodb:
    enabled: true
    spec:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 10Gi
  registry:
    enabled: true
    spec:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 10Gi
