{{- if .Values.ingress.enable }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reportportal-api-ingress
  labels: {{ include "labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end}}
  rules:
{{ if .Values.ingress.usedomainname }}
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host }}
    http:
      paths:
      - path: /api/v1
        backend:
          serviceName: api-0
          servicePort: headless
  {{- end -}}
{{ else }}
  - http:
      paths:
      - path: /api/v1
        backend:
          serviceName: api-0
          servicePort: headless
{{ end }}
status:
  loadBalancer: {}
{{- end }}
