dependencies:
  - name: stable/mongodb
    version: 0.4.18
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mongodb.installdep.enable
  - name: stabele/elasticsearch
    version: 1.17.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: elasticsearchoss.installdep.enable
