# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

traefik:
  repository: traefik
  tag: 1.7.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceindex:
  repository: reportportal/service-index
  tag: 4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
consul:
  repository: consul
  tag: 1.0.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceauthorization:
  repository: reportportal/service-authorization
  tag: 4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  sessionLiveTime: 86400
serviceui:
  repository: reportportal/service-ui
  tag: 4.3.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 4.3.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
serviceapi:
  repository: reportportal/service-api
  tag: 4.3.4
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 300m
      memory: 1500Mi
elasticsearch:
  installdep:
    enable: false
  endpoint:
    external: true
    address: elasticsearch-client.default.svc
    port: 9200
mongodb:
  installdep:
    enable: false
  endpoint: 
    external: true
    address: mongodb://mongodb.default.svc.cluster.local
    port: 27017

# ingress configuration for the ui
ingress:
  hosts:
    - reportportal

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# persistence configuration for elasticsearch, mongodb & consul
persistence:
  registry:
    enabled: false
    ## If true will use an existing PVC instead of creating one
    # useExisting: false
    spec:
      ## consul data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode:
        - ReadWriteOnce
      capacity:
        storage: 2Gi
