# docker registry in which the images are hosted
registry: "" # docker-registry.com

# list of images

traefik:
  repository: traefik
  tag: 1.7.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

serviceindex:
  repository: reportportal/service-index
  tag: 4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
mongodb:
  repository: mongo
  tag: 3.4
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 256m
      memory: 576Mi
consul:
  repository: consul
  tag: 1.0.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceauthorization:
  repository: reportportal/service-authorization
  tag: 4.2.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi
  sessionLiveTime: 86400
serviceui:
  repository: reportportal/service-ui
  tag: 4.3.6
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
serviceanalyzer:
  repository: reportportal/service-analyzer
  tag: 4.3.0
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
serviceapi:
  repository: reportportal/service-api
  tag: 4.3.4
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m
      memory: 1000Mi
    limits:
      cpu: 300m
      memory: 1500Mi
elasticsearchoss:
  repository: docker.elastic.co/elasticsearch/elasticsearch-oss
  tag: 6.1.1
  pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

# ingress configuration for the ui
ingress:
  hosts:
    - reportportal.k8.com

# node selector for all components, if any
nodeSelector:
  enabled: false
  selector:
    reportportal: true

# persistence configuration for elasticsearch, mongodb & consul
persistence:
  elasticsearch:
    enabled: true
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 10Gi
  mongodb:
    enabled: true
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 10Gi
  registry:
    enabled: true
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 10Gi
