apiVersion: v1
kind: Service
metadata:
  name: aggregator
  labels: {{ include "labels" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30036
  selector:
    component: reportportal-aggregator
