apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-elasticsearch
  serviceName: elasticsearch
  template:
    metadata:
      labels:
        component: reportportal-elasticsearch
    spec:
      containers:
      - image: "{{ .Values.elasticsearchoss.repository }}:{{ .Values.elasticsearchoss.tag }}"
        name: elasticsearch
        {{ if .Values.persistence.elasticsearchenabled -}}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: reportportal-elasticsearch
      volumes:
      - name: reportportal-elasticsearch
        persistentVolumeClaim:
          claimName: reportportal-elasticsearch
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
{{- end }}
{{ include "nodeSelector" . | indent 8 }}