apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mongodb
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
      matchLabels:
        component: reportportal-mongodb
  template:
    metadata:
      labels:
        component: reportportal-mongodb
    spec:
      containers:
      - image: "{{ .Values.mongodb.repository }}:{{ .Values.mongodb.tag }}"
        name: mongodb
        resources: {}
        {{ if .Values.persistence.mongodb.enabled -}}

        volumeMounts:
        - mountPath: /data/db
          name: reportportal-mongodb
      volumes:
      - name: reportportal-mongodb
        persistentVolumeClaim:
          claimName: reportportal-mongodb
        resources:
          requests:
            cpu: {{ .Values.mongodb.resources.requests.cpu }}
            memory: {{ .Values.mongodb.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mongodb.resources.limits.cpu }}
            memory: {{ .Values.mongodb.resources.limits.memory }}
{{- end }}
{{ include "nodeSelector" . | indent 8 }}
