apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: registry
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-registry
  serviceName: registry
  template:
    metadata:
      labels:
        component: reportportal-registry
    spec:
      containers:
      - args:
        - agent
        - -server
        - -bootstrap-expect=1
        - -ui
        - -client
        - 0.0.0.0
        env:
        - name: CONSUL_LOCAL_CONFIG
          value: '{"leave_on_terminate": true}'
        image: "{{ .Values.consul.repository }}:{{ .Values.consul.tag }}"
        name: registry
        ports:
        - containerPort: 8500
          protocol: TCP
        resources: {}
        {{ if .Values.persistence.registry.enabled -}}
        volumeMounts:
        - mountPath: /consul/data
          name: reportportal-registry
      volumes:
      - name: reportportal-registry
        persistentVolumeClaim:
          claimName: reportportal-registry
        resources:
          requests:
            cpu: {{ .Values.consul.resources.requests.cpu }}
            memory: {{ .Values.consul.resources.requests.memory }}
          limits:
            cpu: {{ .Values.consul.resources.limits.cpu }}
            memory: {{ .Values.consul.resources.limits.memory }}
{{- end }}
{{ include "nodeSelector" . | indent 8 }}
