apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-uat
  serviceName: uat-0
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - env:
        - name: RP_PROFILES
          value: docker
        - name: RP_SESSION_LIVE
          value: "86400"
        image: "{{ .Values.serviceauthorization.repository }}:{{ .Values.serviceauthorization.tag }}"
        name: uat
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
{{ include "nodeSelector" . | indent 8 }}
