apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-api
  template:
    metadata:
      labels:
        component: reportportal-api
    spec:
      containers:
      - env:
        - name: "JAVA_OPTS"
          value: "-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp"
        - name: "RP_PROFILES"
          value: "docker"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.serviceapi.repository }}:{{ .Values.serviceapi.tag }}"
        name: api
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceapi.resources.requests.cpu }}
            memory: {{ .Values.serviceapi.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceapi.resources.limits.cpu }}
            memory: {{ .Values.serviceapi.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
