apiVersion: apps/v1
kind: Deployment
metadata:
  name: uat
  labels: {{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: reportportal-uat
  template:
    metadata:
      labels:
        component: reportportal-uat
    spec:
      containers:
      - env:
        - name: RP_PROFILES
          value: docker
        - name: RP_SESSION_LIVE
          value: "{{ .Values.serviceauthorization.sessionLiveTime }}"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: "{{ .Values.serviceauthorization.repository }}:{{ .Values.serviceauthorization.tag }}"
        name: uat
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: {{ .Values.serviceauthorization.resources.requests.cpu }}
            memory: {{ .Values.serviceauthorization.resources.requests.memory }}
          limits:
            cpu: {{ .Values.serviceauthorization.resources.limits.cpu }}
            memory: {{ .Values.serviceauthorization.resources.limits.memory }}
{{ include "nodeSelector" . | indent 8 }}
